#
# documents:
# - https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# - https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#deployment-event-deployment
# - https://developer.github.com/v3/repos/deployments/
#

name: dump deployment
on: deployment

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - run: export -p
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Create deployment_status.json with success
        if: success()
        run: |
          cat << JSON > deployment_status.json
          {
            "state": "success"
          }
          JSON
      - name: Create deployment_status.json with failure
        if: "!success()"
        run: |
          cat << JSON > deployment_status.json
          {
            "state": "failure"
          }
          JSON
      - name: POST deployment_statuses
        if: always()
        run: |
          curl -fsS -X POST \
            -H "Accept: application/json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -d @deployment_status.json \
            ${{ github.event.deployment.statuses_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

