#
# documents:
# - https://help.github.com/en/categories/automating-your-workflow-with-github-actions
#

name: dump
on: push

jobs:
  job-0:
    name: Dump env, contexts
    runs-on: ubuntu-latest
    steps:
      - run: export -p
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  job-1:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -lahR -I .git
      - run: git status
      - run: git remote -v

  job-2:
    name: Dump OS info
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/os-release
      - run: uname -a
      - run: id -a
      - run: cat /proc/cpuinfo
      - run: free -m
      - run: cat /proc/meminfo
      - run: df -T -h
      - run: cat /proc/mounts
      - run: ip a show
      - run: ps -ef fww
      - run: apt list --installed
      - name: Show apt-lines
        run: |
          for f in /etc/apt/sources.list $(find /etc/apt/sources.list.d -name \*.list); do
            echo '>>> --------------------------------------------------------------------------------'
            echo ">>> $f"
            echo '>>> --------------------------------------------------------------------------------'
            echo
            cat $f
            echo
          done
      - name: List commands in PATH
        run: |
          for d in $(echo $PATH | sed -e 's/:/ /g'); do
            if [ -d $d ]; then
              echo '>>> --------------------------------------------------------------------------------'
              echo ">>> $d"
              echo '>>> --------------------------------------------------------------------------------'
              echo
              ls -lah $d
              echo
            fi
          done

  job-3:
    name: Ohai
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends ohai
      - run: sudo ohai

  job-4:
    name: Dump docker info
    runs-on: ubuntu-latest
    steps:
      - run: docker --version
      - run: docker version
      - run: docker system info
      - run: docker system df
      - run: docker image ls -a
      - run: docker container ls -a
      - run: docker network ls
      - run: docker volume ls
      - run: docker plugin ls

  job-5:
    name: Slack
    runs-on: ubuntu-latest
    steps:
      - uses: k0kubun/action-slack@v2.0.0
        with:
          payload: |
            {
              "username": "GitHub Actions",
              "icon_emoji": ":octocat:",
              "channel": "#notification",
              "attachments": [{
                "color": ("${{ job.status }}" == "Success" ? "good" : "danger"),
                "text": "${{ job.status }}: Workflow ${{ github.workflow }} (<${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}|#${{ github.run_number }}>)",
                "footer": "<${{ github.event.repository.html_url }}|${{ github.repository }}>",
                "footer_icon": "https://github.githubassets.com/favicon.ico",
                "fields": [
                  {
                    "title": "github.ref",
                    "value": "<${{ github.event.repository.html_url }}/tree/" + "${{ github.ref }}".replace(/^refs\/(heads|tags)\//, '') + "|${{ github.ref }}>",
                    "short": true
                  },
                  {
                    "title": "github.sha",
                    "value": "<${{ github.event.repository.html_url }}/commit/${{ github.sha }}|" + "${{ github.sha }}".substring(0, 10) + ">",
                    "short": true
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: "always()"


