#
# documents:
# - https://help.github.com/en/categories/automating-your-workflow-with-github-actions
#

name: dump
on: push

jobs:
  dump:
    name: dump
    runs-on: ubuntu-latest
    steps:
      - run: export -p

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: List packages
        run: dpkg -l

      - name: List commands in PATH
        run: |
          for d in $(echo $PATH | sed -e 's/:/ /g'); do
            if [ -d $d ]; then
              echo ">>> $d"
              ls -lah $d
              echo
            fi
          done

      - name: Install ohai
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ohai

      - name: Run ohai
        run: sudo ohai

